---
book_repo: cloudfoundry/docs-book-cloudfoundry

broken_link_exclusions: iefix|arrowhead|#
repo_link_enabled: true
elastic_search: true

public_host: docs.cloudfoundry.org

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

products:
  - id: oss
    subnav_root: deploying/subnav-index.html

sections:
- repository:
    name: cloudfoundry/docs-cloudfoundry-concepts
  directory: concepts
  product_id: oss
- repository:
    name: cloudfoundry/docs-dev-guide
  directory: devguide
  product_id: oss
- repository:
    name: cloudfoundry/docs-cf-cli
  directory: cf-cli
  product_id: oss
- repository:
    name: cloudfoundry/docs-cf-admin
  directory: adminguide
  product_id: oss
- repository:
    name: cloudfoundry/docs-services
  directory: services
  product_id: oss
- repository:
    name: cloudfoundry/docs-deploying-cf
  directory: deploying
  product_id: oss
- repository:
    name: cloudfoundry/docs-bosh
  directory: bosh
  product_id: oss
- repository:
    name: cloudfoundry/docs-running-cf
  directory: running
  product_id: oss
- repository:
    name: cloudfoundry/docs-buildpacks
  directory: buildpacks
  product_id: oss
- repository:
    name: cloudfoundry/docs-loggregator
  directory: loggregator
  product_id: oss
